-- role
CREATE TABLE role (
   id bigserial PRIMARY KEY,
   created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
   version serial NOT NULL,

    name VARCHAR(35) NOT NULL
);