spring:
  datasource:
    url: &dbURL jdbc:postgresql://localhost:5432/kaesseli
    username: &dbUser dbuser
    password: &dbPassword mysecretpassword
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres
logging:
  level:
    root: WARNING
    org.springframework.web: DEBUG
    org.hibernate: DEBUG