spring:
  datasource:
    platform: postgres
    #driverClassName: org.mariadb.jdbc.Driver
    #url: &dbURL jdbc:mariadb://localhost:3306/kaesseli
    url: &dbURL jdbc:postgresql://localhost:5432/kaesseli
    username: &dbUser dbuser
    password: &dbPassword mysecretpassword
  flyway:
    locations: classpath:db/migrations
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update